# TCL File Generated by Component Editor 7.2 on:
# Mon Feb 04 13:31:56 CST 2008
# DO NOT MODIFY

set_source_file "openeth.v"
set_module "openeth"
set_module_description "Opencores ethernet mac"
set_module_property "className" "opencores_ethernet_mac"
set_module_property "displayName" "opencores_ethernet_mac"
set_module_property "group" "Interface Protocols/Ethernet"
set_module_property "synthesisFiles" "openeth.v"

# Module parameters

# Interface clock_sink
add_interface "clock_sink" "clock" "sink" "asynchronous"
# Ports in interface clock_sink
add_port_to_interface "clock_sink" "clk" "clk"
add_port_to_interface "clock_sink" "reset" "reset"

# Interface s
add_interface "s" "avalon" "slave" "clock_sink"
set_interface_property "s" "isNonVolatileStorage" "false"
set_interface_property "s" "burstOnBurstBoundariesOnly" "false"
set_interface_property "s" "readLatency" "0"
set_interface_property "s" "readWaitStates" "0"
set_interface_property "s" "holdTime" "0"
set_interface_property "s" "printableDevice" "false"
set_interface_property "s" "readWaitTime" "0"
set_interface_property "s" "setupTime" "0"
set_interface_property "s" "addressAlignment" "NATIVE"
set_interface_property "s" "writeWaitTime" "0"
set_interface_property "s" "timingUnits" "Cycles"
set_interface_property "s" "minimumUninterruptedRunLength" "1"
set_interface_property "s" "isMemoryDevice" "false"
set_interface_property "s" "linewrapBursts" "false"
set_interface_property "s" "maximumPendingReadTransactions" "0"
# Ports in interface s
add_port_to_interface "s" "s_readdata" "readdata"
add_port_to_interface "s" "s_waitrequest" "waitrequest"
add_port_to_interface "s" "s_address" "address"
add_port_to_interface "s" "s_chipselect" "chipselect"
add_port_to_interface "s" "s_write" "write"
add_port_to_interface "s" "s_read" "read"
add_port_to_interface "s" "s_byteenable" "byteenable"
add_port_to_interface "s" "s_writedata" "writedata"

# Interface m
add_interface "m" "avalon" "master" "clock_sink"
set_interface_property "m" "burstOnBurstBoundariesOnly" "false"
set_interface_property "m" "doStreamReads" "false"
set_interface_property "m" "linewrapBursts" "false"
set_interface_property "m" "doStreamWrites" "false"
# Ports in interface m
add_port_to_interface "m" "m_read" "read"
add_port_to_interface "m" "m_write" "write"
add_port_to_interface "m" "m_writedata" "writedata"
add_port_to_interface "m" "m_waitrequest" "waitrequest"
add_port_to_interface "m" "m_readdata" "readdata"
add_port_to_interface "m" "m_address" "address"
add_port_to_interface "m" "m_byteenable" "byteenable"

# Interface interrupt_sender
add_interface "interrupt_sender" "interrupt" "sender" "clock_sink"
set_interface_property "interrupt_sender" "associatedAddressablePoint" "s"
# Ports in interface interrupt_sender
add_port_to_interface "interrupt_sender" "s_irq" "irq"

# Interface conduit_start
add_interface "conduit_start" "conduit" "start" "clock_sink"
# Ports in interface conduit_start
add_port_to_interface "conduit_start" "tx_d" "export"
add_port_to_interface "conduit_start" "tx_en" "export"
add_port_to_interface "conduit_start" "tx_err" "export"
add_port_to_interface "conduit_start" "md_c" "export"
add_port_to_interface "conduit_start" "md_out" "export"
add_port_to_interface "conduit_start" "md_oe" "export"

# Interface conduit_end
add_interface "conduit_end" "conduit" "end" "clock_sink"
# Ports in interface conduit_end
add_port_to_interface "conduit_end" "tx_clk" "export"
add_port_to_interface "conduit_end" "rx_clk" "export"
add_port_to_interface "conduit_end" "rx_d" "export"
add_port_to_interface "conduit_end" "rx_dv" "export"
add_port_to_interface "conduit_end" "rx_err" "export"
add_port_to_interface "conduit_end" "rx_col" "export"
add_port_to_interface "conduit_end" "rx_crs" "export"
add_port_to_interface "conduit_end" "md_in" "export"
